### ISSUE TITLE
ResourcesNotFoundException in MessagesFeedbackViewHolder.java line 73

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#14]
After updating to v2.3, we are getting below crash. We have set `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)` in our Application class as our app supports API 19.  Please look into this issue. Thanks!

```
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable/salesiq_vector_happy.xml from drawable resource ID #0x7f0803f7. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
       at android.content.res.Resources.loadDrawable(Resources.java:3451)
       at android.content.res.Resources.getDrawable(Resources.java:1894)
       at com.zoho.livechat.android.ui.adapters.viewholder.MessagesFeedbackViewHolder.render(MessagesFeedbackViewHolder.java:73)
       at com.zoho.livechat.android.ui.adapters.MessagesAdapter.onBindViewHolder(MessagesAdapter.java:396)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2151)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1862)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

```
Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
       at android.content.res.Resources.loadDrawable(Resources.java:3447)
       at android.content.res.Resources.getDrawable(Resources.java:1894)
       at com.zoho.livechat.android.ui.adapters.viewholder.MessagesFeedbackViewHolder.render(MessagesFeedbackViewHolder.java:73)
       at com.zoho.livechat.android.ui.adapters.MessagesAdapter.onBindViewHolder(MessagesAdapter.java:396)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2151)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1862)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Angu-G** [comment]
Fix is available in version 2.3.1.

dependency:
implementation 'com.zoho.salesiq:mobilisten:2.3.1'
