### ISSUE TITLE
IllegalStateException in  LiveChatAdapter.java line 307 

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#23]
Getting below error in Zoho Mobilisten SDK.  SDK version used in 2.3.1.

```
Fatal Exception: java.lang.IllegalStateException: Timer already cancelled.
       at java.util.Timer.sched(Timer.java:397)
       at java.util.Timer.schedule(Timer.java:193)
       at com.zoho.livechat.android.comm.LiveChatAdapter$WMSPEXConnectionHandler.schedule(LiveChatAdapter.java:307)
       at com.zoho.livechat.android.comm.LiveChatAdapter$WMSPEXConnectionHandler.access$800(LiveChatAdapter.java:254)
       at com.zoho.livechat.android.comm.LiveChatAdapter$WMSPEXConnectionHandler$1.run(LiveChatAdapter.java:319)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

<img width="1134" alt="Screenshot 2021-02-09 at 3 49 34 PM" src="https://user-images.githubusercontent.com/8415897/107349629-72759000-6aee-11eb-913b-49504b222326.png">

**Comment by alokvnair** [comment]
Please do let me know if you need complete stack trace of the crash.

**Comment by Angu-G** [comment]
@alokvnair, We are checking the issues you reported.

**Comment by Angu-G** [comment]
The fix for this issue will be rolled out in our next update @alokvnair. Thank you

**Comment by Angu-G** [comment]
@alokvnair, We have a new version [v2.3.2](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/3.0) with the fix. Please try it out and let us know. Closing the issue here.
