### ISSUE TITLE
android.database.CursorWindowAllocationException  in ChatFragment.java line 2633 

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#24]
Getting below error in Zoho Mobilisten SDK. SDK version used in 2.3.1.

```
Fatal Exception: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.noonEdu.k12App/databases/siq_mobilisten.db' of size 4194304 due to error -12.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:145)
       at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:319)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:159)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
       at com.zoho.livechat.android.ui.fragments.ChatFragment.shouldHideInput(ChatFragment.java:2633)
       at com.zoho.livechat.android.ui.fragments.ChatFragment.canEnableSendButton(ChatFragment.java:3466)
       at com.zoho.livechat.android.ui.fragments.ChatFragment.setSendInputButtonState(ChatFragment.java:3410)
       at com.zoho.livechat.android.ui.fragments.ChatFragment.afterTextChanged(ChatFragment.java:3368)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:11664)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:14910)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:618)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:393)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

<img width="1142" alt="Screenshot 2021-02-09 at 3 52 33 PM" src="https://user-images.githubusercontent.com/8415897/107349969-dc8e3500-6aee-11eb-9f71-fbaf4da4756d.png">

**Comment by Angu-G** [comment]
This issue will be followed up with #25. Closing here.
