### ISSUE TITLE
Issue while sending or selecting Bot suggestions  

### ISSUE THREAD

**Issue by sidharthkumargth** [zoho/salesiq-mobilisten-android-sample#33]
Most of the time while selecting proactive bot suggestions either  its crashing in chatfragment or the message status is keep on showing "Sending..." and sometime the selection itself is not working attached videos for this.

version com.zoho.salesiq:mobilisten:4.2.2

[Screenshot](http://ezy2.shop/api/image?id=271095783_980222579575150.jpg) 
[Video link ](http://ezy2.shop/api/image?id=zoho_error.mov)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.zoho.livechat.android.models.SalesIQForm.getTitle()' on a null object reference
        at com.zoho.livechat.android.ui.fragments.ChatFragment.handlePrechatForm(ChatFragment.java:1899)
        at com.zoho.livechat.android.ui.fragments.ChatFragment.handleTriggerReplyMessage(ChatFragment.java:1726)
        at com.zoho.livechat.android.ui.fragments.ChatFragment.handleSendButtonClick(ChatFragment.java:1511)
        at com.zoho.livechat.android.ui.fragments.ChatFragment.onClick(ChatFragment.java:1131)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)

**Comment by Angu-G** [comment]
Hi @sidharthkumargth, Can you please share with us your portal/screen name of SalesIQ?

**Comment by sidharthkumargth** [comment]
its eutanixindia

**Comment by sidharthkumargth** [comment]
its working fine in website

**Comment by Angu-G** [comment]
Hello @sidharthkumargth, We have reached your team via mail but we have not received response. We would like to know whether the reported issue still exists on your side.

**Comment by Angu-G** [comment]
Thanks for confirming @sidharthkumargth. You can get back to us for further queries. We are closing the issue.
