### ISSUE TITLE
Launcher icon (FAB button with a messaging icon) show the first time app is installed

### ISSUE THREAD

**Issue by Fraid** [zoho/salesiq-mobilisten-android-sample#35]
Hi Team,

Following error appear in log on first install of app. 

```
 E/System: java.util.zip.ZipException: File too short to be a zip file: 0
        at java.util.zip.ZipFile.<init>(ZipFile.java:214)
        at java.util.zip.ZipFile.<init>(ZipFile.java:148)
        at java.util.jar.JarFile.<init>(JarFile.java:161)
        at java.util.jar.JarFile.<init>(JarFile.java:98)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:532)
        at dalvik.system.DexPathList$Element.findNativeLibrary(DexPathList.java:546)
        at dalvik.system.DexPathList.findLibrary(DexPathList.java:480)
        at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:84)
        at xtr.a(:com.google.android.gms@214815017@21.48.15 (040306-414534850):6)
        at xtr.g(:com.google.android.gms@214815017@21.48.15 (040306-414534850):4)
        at xtr.f(:com.google.android.gms@214815017@21.48.15 (040306-414534850):2)
        at com.google.android.gms.providerinstaller.ProviderInstallerImpl.b(:com.google.android.gms@214815017@21.48.15 (040306-414534850):6)
        at com.google.android.gms.providerinstaller.ProviderInstallerImpl.insertProvider(:com.google.android.gms@214815017@21.48.15 (040306-414534850):5)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(:com.google.android.gms@214815017@21.48.15 (040306-414534850):2)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.security.ProviderInstaller.zzc(com.google.android.gms:play-services-basement@@18.0.0:2)
        at com.google.android.gms.security.ProviderInstaller.installIfNeeded(com.google.android.gms:play-services-basement@@18.0.0:12)
        at com.zoho.livechat.android.ZohoLiveChat.init(ZohoLiveChat.java:119)
        at com.zoho.salesiqembed.ZohoSalesIQ.init(ZohoSalesIQ.java:62)
        at ----------------------------------------------------
        at -------------------------------------------------------Application.java:144)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5475)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6196)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

Then when doing `ZohoSalesIQ.Chat.show();` FAB button  will appear for some reason but then nothing .
Call `ZohoSalesIQ.Chat.show();` a second time will show the conversation, however to remove the FAB button, I need to close the app.

Our project have everything up to date including _Android Studio_, _gradle_, _androidx_ etc. Not the case with your sample so it's little hard to do the diff.

I do use ProviderInstaller with method "ProviderInstaller.installIfNeededAsync" and I try to do `ZohoSalesIQ.init` in `onProviderInstalled` but same error showing.

The weird thing is that default value for `ZohoSalesIQ.showLauncher(...);` is `false` so shouldn't show anyway. 

And finally I try to call `ZohoSalesIQ.showLauncher(...);` in both case after _`ZohoSalesIQ.init`_ and in _`onInitComplete`_.

I think the best way to reproduce the issue would be by faking an exception here:
```
   try {
        
          // You got the idea here what will happen to your library if I got an exception the first time?
            ProviderInstaller.installIfNeeded(context);
        
         } catch (GooglePlayServicesRepairableException var11) {
            Log.e("Mobilisten", var11.getMessage(), var11);
         } catch (GooglePlayServicesNotAvailableException var12) {
            Log.e("Mobilisten", var12.getMessage(), var12);
         }catch (Exception e) {
          // not sure but could that be an hotFix?
         }
```

Tested on a Pixel 3, old phone with android 7.1.1 and emulator.

I just don't want to see the FAB button appearing.

Edit: Tested with version zoho 4.2.3 and 4.2.2

**Comment by Angu-G** [comment]
Hello @Fraid, The misbehavior of the showLauncher() might be due to the exception that is because of ProviderInstaller.  We like to debug more on this, Can you please mail us at **support@zohosalesiq.com** to have a session.

**Comment by Angu-G** [comment]
Hi @Fraid, Thanks for your time over the session. As we said the misbehaviour of the showLauncher() API is because the registerVisitor() API is triggered after showLauncher(). We will be clearing the previous configs when registerVisitor() is triggered. This is because we should not preserve the data of previously registered visitor to the current visitor. 
As we guided, You can trigger APIs only after registerVisitor() call to make it countable for the current visitor. 
You can get back to us for further queries in future.
