### ISSUE TITLE
Getting Random crash from Zoho SDK

### ISSUE THREAD

**Issue by JackeyPSSPL** [zoho/salesiq-mobilisten-android-sample#45]
Hello Support team,

Getting a random crash like below so could you please help for it and give suggestion what solution we need to apply. Currently using Zoho SDK version is **8.0.3.**

crash is:

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@5015242[Not completed] rejected from java.util.concurrent.ThreadPoolExecutor@9ac5253[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
                                                                                                    	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
                                                                                                    	at com.zoho.livechat.android.utils.LiveChatUtil.setCVUID(LiveChatUtil.java:260)
                                                                                                    	at com.zoho.livechat.android.ZohoLiveChat.unregisterVisitor(ZohoLiveChat.java:628)
                                                                                                    	at                                                                                                     	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@925fd29, Dispatchers.Default]
                                                                                                    	
user for unregister in our app logout we are doing this
**ZohoSalesIQ.unregisterVisitor(context)**

**Comment by bhahirathan-mb-11956** [comment]
Hi @JackeyPSSPL ,
 
We apologize for the inconvenience caused. We'll look into this crash and update you.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @JackeyPSSPL,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [8.0.7](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/v8.0.7), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M
Zoho SalesIQ.
