### ISSUE TITLE
Getting issue into Chat Activity

### ISSUE THREAD

**Issue by JackeyPSSPL** [zoho/salesiq-mobilisten-android-sample#46]
Hello Team,

Please check we are getting crash on Chat activity. here not able to reproduced but on my crashlytics logs getting error of some user.
Currently used version: **8.0.3** 

crash log

 Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1632)
       at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1672)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
       at com.zoho.livechat.android.ui.activities.ChatActivity.openFragment(ChatActivity.kt:434)
       at com.zoho.livechat.android.ui.activities.ChatActivity$initChat$1$1.invokeSuspend(ChatActivity.kt:415)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by bhahirathan-mb-11956** [comment]
Hi @JackeyPSSPL ,
 
We apologize for the inconvenience caused. The issue has already been fixed. Please update the Mobilisten SDK to the [latest version](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/latest) and verify once.
 
Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by JackeyPSSPL** [comment]
Thank you @bhahirathan-mb-11956 for quick response.
