### ISSUE TITLE
Getting Crash "java.util.concurrent.RejectedExecutionException" doing unregisterVisitor

### ISSUE THREAD

**Issue by JackeyPSSPL** [zoho/salesiq-mobilisten-android-sample#48]
Used code is like below
 **ZohoSalesIQ.unregisterVisitor(context)**
 
 **Crash:**
 Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@203c46a[Not completed] rejected from java.util.concurrent.ThreadPoolExecutor@a57d029[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
       at com.zoho.livechat.android.utils.LiveChatUtil.setCVUID(LiveChatUtil.java:260)
       at com.zoho.livechat.android.ZohoLiveChat.unregisterVisitor(ZohoLiveChat.java:628)
       at com.utils.CommonUtil$logoutUser$1.invokeSuspend(CommonUtil.kt:125)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)

**Comment by bhahirathan-mb-11956** [comment]
Hi @JackeyPSSPL ,

We apologize for the inconvenience caused. We'll look into this crash and update you.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @JackeyPSSPL,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [8.0.7](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/v8.0.7), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M
Zoho SalesIQ.
