### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#6]
Getting crash logged related to ActivityNotFoundException in Crashlytics for SalesIQ Mobilisten SDK. Please check and fix this

> Fatal Exception: android.content.ActivityNotFoundException
> No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.google.com/... }
> com.zoho.livechat.android.ui.adapters.viewholder.MessagesTextViewHolder$2.onClick

**Stack Trace:**

`Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.google.com/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1854)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
       at android.app.Activity.startActivityForResult(Activity.java:4391)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at android.app.Activity.startActivityForResult(Activity.java:4335)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
       at android.app.Activity.startActivity(Activity.java:4702)
       at android.app.Activity.startActivity(Activity.java:4670)
       at com.zoho.livechat.android.ui.adapters.viewholder.MessagesTextViewHolder$2.onClick(MessagesTextViewHolder.java:124)
       at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
       at android.widget.TextView.onTouchEvent(TextView.java:8827)
       at android.view.View.dispatchTouchEvent(View.java:10012)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
       at android.view.View.dispatchPointerEvent(View.java:10232)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4862)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4723)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4255)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4308)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4274)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4401)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4282)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4458)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4255)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4308)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4274)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4282)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4255)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6682)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6656)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6617)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6809)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:356)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

**Comment by Angu-G** [comment]
@alokvnair This crash occurred when the user tried to open link url from the message since the given link doesn't have an appropriate app or default browser in the user's device to navigate. We will handle this exception with a proper error message in the next immediate update.

**Comment by alokvnair** [comment]
Any updates on this @Angu-G ? We are getting this issue being reported too much.

**Comment by Angu-G** [comment]
@alokvnair, This issue has been fixed in version **2.3-beta.2**. We will be rolling this out as a major release soon.

**Comment by alokvnair** [comment]
Is the stable version released @Angu-G

**Comment by Angu-G** [comment]
@alokvnair ,  It can be expected in the second week of September.

**Comment by alokvnair** [comment]
Is this release planned for Sep 2nd week done @Angu-G ? Please update

**Comment by Angu-G** [comment]
It is live @alokvnair . Thanks for your patience.
