### ISSUE TITLE
NullPointerException in ChatFragment.java

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#9]
After updating to v2.3, we are getting below crash. Please look into this issue. Thanks!
 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeMessages(int)' on a null object reference
       at com.zoho.livechat.android.ui.fragments.ChatFragment.onTextChanged(ChatFragment.java:3394)
       at android.widget.TextView.sendOnTextChanged(TextView.java:9771)
       at android.widget.TextView.handleTextChanged(TextView.java:9868)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12576)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1263)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:575)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6703)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by alokvnair** [comment]
Same as https://github.com/zoho/salesiq-mobilisten-android-sample/issues/12. Added info there
